### PR TITLE
fix: `tsconfig.json` edge-cases in dependencies

### LINKED ISSUE #363: File '@ljharb/tsconfig' not found.
### Problem

I was using the 4.0.3 version before but since yesterday it has been reporting an error

The code and module that went wrong have been identified through both projects, but I didn't find out whose dependency this error message is from

```
qs -> side-channel -> get-intrinsic -> es-errors
```

image

```
jsonwebtoken -> jws -> util
```

image

If you use esbuild-loader with the above 2 modules in your project, you get the error

```
Error: File '@ljharb/tsconfig' not found.
    at je (/Users/zhengxs/demo/node_modules/get-tsconfig/dist/index.cjs:3:9102)
    at te (/Users/zhengxs/demo/node_modules/get-tsconfig/dist/index.cjs:3:10066)
    at ie (/Users/zhengxs/demo/node_modules/get-tsconfig/dist/index.cjs:3:10781)
    at Object.$e [as getTsconfig] (/Users/zhengxs/demo/node_modules/get-tsconfig/dist/index.cjs:3:10886)
    at Object.ESBuildLoader (/Users/zhengxs/demo/node_modules/esbuild-loader/dist/index.cjs:65:36)
    at LOADER_EXECUTION (/Users/zhengxs/demo/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/Users/zhengxs/demo/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/Users/zhengxs/demo/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at /Users/zhengxs/demo/node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

### Expected behavior

Bundle Success

### Minimal reproduction URL

https://stackblitz.com/edit/node-gcfggk?file=package.json

### Version

v4.0.3

### Node.js version

v16.0.0

### Package manager

yarn

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

### PR DESCRIPTION
**Pull request by glsignal**
Fixes #363 where esbuild-loader would resolve the tsconfig.json of external files under certain conditions, which most recently became a problem when one of these configs included an `extends` option that referenced a package not in the project's dependency tree, making it impossible to resolve.

The patch changes this behaviour and will attempt to resolve the tsconfig.json still, however when it encounters a problem, if the resource associated with the tsconfig is a third party dependency, it will suppress the error and log a warning instead of bailing.

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks for the PR!

RE: [fix(dev): prevent fs-fixture causing a re-run loop](https://github.com/privatenumber/esbuild-loader/commit/351fc8261d6b877644291e2236c147ad55f58e30)

Can you provide env details? (OS, tooling versions, etc) I haven't needed this before.

**Comment by glsignal** [comment]
Sure thing!

OS: `Linux lovelace 6.9.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000 x86_64 GNU/Linux`
Node: v20.14.0
pnpm: 9.2.0 (via corepack)

It might well be a linux thing (happy to rebase without that commit), but here's what the problem looked like for me in case it gives any additional insight

image

**Comment by glsignal** [comment]
I removed the commit that introduced the `--ignore /tmp` since the issue (if it's an issue) doesn't seem to be related to this project/PR, and have set up a reproduction in https://github.com/glsignal/fs-fixture-tsx-watch-loop
(edit: and it's only looping on my linux machines, seems fine in macos)

File: src/loader.ts [hunk 1]
```diff
@@ -81,6 +81,12 @@ async function ESBuildLoader(
 		} else {
 			/* Detect tsconfig file */
 
+			// Don't look for tsconfig.json based on external sources (see
+			// https://github.com/privatenumber/esbuild-loader/issues/363)
+			if (resourcePath.match(/node_modules/) !== null) {
```
Comment (privatenumber) [inline src/loader.ts]:
```suggestion
			if (resourcePath.includes('/node_modules/')) {
```

This could catch something like `node_modules_file`. I'm wondering if my suggestion would work on Windows where they use blackslashes... the tests will tell

File: tests/specs/tsconfig.ts [hunk 2]
```diff
@@ -263,6 +263,78 @@ export default testSuite(({ describe }) => {
 				const code2 = await fixture.readFile('dist/index2.js', 'utf8');
 				expect(code2).toMatch('__publicField(this, "foo", 100);');
 			});
+
+			test('ignores tsconfig.json in third party dependencies', async () => {
+				await using fixture = await createFixture({
+					// Fake external dependency
+					node_modules: {
+						'fake-lib': {
+							'index.js': 'export function testFn() { return "Hi!" }',
```
Comment (privatenumber) [inline tests/specs/tsconfig.ts]: Can you make this a `.ts` file to confirm TS files in node_modules can still be compiled?

**Comment by privatenumber** [comment]
Sorry about the linting/type-check errors. I fixed them in the `master` branch directly.

It looks like this PR no longer compiles TS in node_modules, but we actually still want to compile them. To do this, we'll probably try to read the tsconfig.json file, but we should ignore any tsconfig errors in `node_modules`.

**Comment by glsignal** [comment]
> It looks like this PR no longer compiles TS in node_modules, but we actually still want to compile them. To do this, we'll probably try to read the tsconfig.json file, but we should ignore any tsconfig errors in node_modules.

Thanks! I'd completely changed the behaviour without realising by using that early return statement.

I've pushed a change which should still try to apply the transform and log a warning if the tsconfig fails to load for some reason. In short, it shouldn't change any behaviour _except_ for when the tsconfig fails to resolve specifically for resources somewhere in node_modules

> Can you make this a .ts file to confirm TS files in node_modules can still be compiled?

~~Where I'm running into trouble is putting together the test case with specifically `.ts` source in the package, any path that points to `.ts` source fails to resolve (`Module not found: Error: Can't resolve './testFn'` etc.)~~

~~I must admit this is an area where I'm not as knowledgeable about the inner workings of module resolution to have a good idea of how to write the appropriate setup for it, do you have any advice here?~~

Never mind that, they're now `.ts` sources in the test

File: src/loader.ts (hunk 1 above)
Comment (glsignal) [reply src/loader.ts]: Great point, thanks for catching this! In the latest commit, I changed the search a little and hopefully the `path.sep` tactic means it is a little more portable

File: tests/specs/tsconfig.ts (hunk 2 above)
Comment (glsignal) [reply tests/specs/tsconfig.ts]: Done!

**Comment by glsignal** [comment]
(fyi; squashed/rebased for a tidier history - no other changes)

File: src/loader.ts [hunk 3]
```diff
@@ -81,8 +81,21 @@ async function ESBuildLoader(
...
+			let tsconfig;
+
+			try {
+				// Webpack shouldn't be loading the same path multiple times so doesn't need to be cached
+				tsconfig = getTsconfig(resourcePath, 'tsconfig.json', tsconfigCache);
+			} catch (error) {
+				if (resourcePath.split(path.sep).includes('node_modules')) {
+					this.emitWarning(
+						new Error(`[esbuild-loader] Error while discovering tsconfig.json in dependency: "${error?.toString()}"`),
+					);
```
Comment (glsignal) [inline src/loader.ts]: I tend to log more by default for cases such as these, but I'd defer to your preference as the maintainer of the project. Do you think there's value in logging this, or would it be preferable to silently ignore it?

For the original issue that sparked this PR, I don't think it would be a directly actionable warning but may provide a breadcrumb if someone is debugging an unusual output

Comment (privatenumber) [reply src/loader.ts]: I think it's a good idea. I would appreciate it as a user.

For the original issue, I think the warning should direct the users to report bugs to the appropriate repo.

I'll update the error message in `get-tsconfig` to be more specific about which file it's trying to resolve.

**Comment by privatenumber** [comment]
I made several changes:
- Only search for a `tsconfig.json` if the file is in the local project, or if it's a dependency with a TS extension
- Only apply provided tsconfig path to files in local project
- Added 2 more tests to cover these cases

**Comment by privatenumber** [comment]
Thanks for the PR and collaboration @glsignal! Appreciate your contribution 🙏

**Comment by glsignal** [comment]
Thank you for the support and pushing it over the finish line @privatenumber! Great collab 😄

**Comment by Seenivasan13** [comment]
Screenshot 2024-11-25 171620
 who to solve this error. please kindly respond me
